# Generated by Django 3.0.1 on 2019-12-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latest_videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_db',
            old_name='index',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='main_db',
            old_name='video_url',
            new_name='video_id',
        ),
    ]
